language: java
sudo: false
addons:
  sonarcloud:
    organization: marcosbarbero-github
    token:
      secure: bvw/c//IhNlSDnC7RS2HvzwKO1vXaW1c7FWudiiiRF2UNc7iwPyyT7pdTkFZB0DALKVeCowmh5uW3kZr5bCfOthRfXYtJ6UcD98BzkVSBdoDdpuKGC/En2nhOIHUMJe8kv4SYW3ulqNI76sjkG8GduR4fwF+uH5biHs9OrihA8OMuJ71hw09TSdqNIANmi5hjakH4DLeGFtrV8i5yMYvXsfGENmIwWSIBmfRmmQ0ksDwG/2JB1B2aeOzR4O/WTUj7TFpXvoyJ7/ccJCnMJ4zeXbizriFiuO+Db/BZvhTeTlu02wu0Is9xjl3y8ohmERffgXv4C0uWgTEBW0SA0rYcmvc83xHVtaLPSPDgmGo9WtkiXYcfMOvI8U07eGne86eL0gHkTNt7y55H98OWi4T2MT1yKov3c0sd5ejcBxoZIIM/bfQuqVM/EWTocu/JBrtAxO5zUX01m3uyLxe17ghTmO2Grryilhz2MA+a8PgfrNQMZL8s/RCUW5S+iUfyRcsC88H4OSUqKA6txp2OR5UcCVhcNx5QtVvapwGm6yvm7WSHc0iq62OHgB8ec6N2hV+lfZecSNn4eULs2sjwCoD9GHk4d5N1zw4iOarKaGgjp5qqizjxVKa3JkY8cTajYsfQGboCTDIpLF87drLtnwth9naqLHVTNHF9RElHwWWAl0=
jdk:
- oraclejdk8
install:
- mvn install -Dmaven.test.skip=true
after_success:
- mvn -pl '!spring-cloud-zuul-ratelimit-dependencies' clean jacoco:prepare-agent verify
  jacoco:report coveralls:report
- mvn -pl '!spring-cloud-zuul-ratelimit-dependencies' package sonar:sonar
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
notifications:
  email:
  - marcos.hgb@gmail.com
env:
  global:
    secure: B5QVZ6SWzgQmlKmStQCHg0RcQPVbkti2Z3s5vi1gR0Oef6KYxBpkzP87yES08OvHG7Ha6XfJ28feML8URtTcdhBtkr4aKMGy9R+VvY9i7hykPLGnuejip89oTt4k8SlWkqmvzx4G6qB1YbooVdAbvaqARlS+t1RjSfOJU5kIBMyyrBshxPlavfzDp55tUcBrfbDEbQmdnRY84gXng+gz+ceJTzg/vxNPyKCcG5Ap/2qW0lH+ZRcJTUgtmNZZIpiw56YD3T/ltc3wVIHEgFzCGUiZAaRtHJW3PGComDKd9Z3JPaZO1nuJlD999Kok4I9IEZjpu7g1mXlaioYsAwholJTsugoinEZ6JChaeT/92ZWY1Ua0vT5YJjz0QCGzlhJ12I751QFk1Lam9hwlhZ7LafDi1p8vhQuN1I5NOulgnoXwZboZ9/2jbNp63o1nq773jULJiAsMXY+Pv8SLCNKzVANyEK9ECYKG3DSxuVLIpX/j1cYWf/UH5FxQ5aiDYnZpBVblWfsQxPuyVjHnIyaAvw4LsTq4DfRG8JMqjjGr0IUGV6Xa/6/hCfx5ojvWFQ17YJeGHJMGAfPwvsTPhLTNl6Wm1Iw6Lt3N9KJ6VaGnJDuza/mJuTrTAdGhZ28bcevNq03vW3bFenLh0EC8zamBBA9eNuqqDak6Q1OzV3z6dRo=
