language: java

dist: trusty

jdk:
 - oraclejdk11

os: linux

script:
 - ./mvnw --settings .ci/settings.xml install -Dmaven.test.skip=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V -q
 
install:
 - ./mvnw --settings .ci/settings.xml install -Dmaven.test.skip=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V -q

before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi

after_success:
 - ./mvnw -pl '!spring-cloud-zuul-ratelimit-dependencies' clean org.jacoco:jacoco-maven-plugin:prepare-agent verify jacoco:report coveralls:report -q -Dlogging.level.root=ERROR

cache:
  directories:
    - $HOME/.m2/repository

notifications:
  email:
    - marcos.hgb@gmail.com
    - lchayoun@gmail.com

deploy:
 - provider: script
   script: bash .ci/deploy.sh
   on:
     branch: master
     repo: marcosbarbero/spring-cloud-zuul-ratelimit
     jdk: oraclejdk11

env:
  global:
  - secure: B5QVZ6SWzgQmlKmStQCHg0RcQPVbkti2Z3s5vi1gR0Oef6KYxBpkzP87yES08OvHG7Ha6XfJ28feML8URtTcdhBtkr4aKMGy9R+VvY9i7hykPLGnuejip89oTt4k8SlWkqmvzx4G6qB1YbooVdAbvaqARlS+t1RjSfOJU5kIBMyyrBshxPlavfzDp55tUcBrfbDEbQmdnRY84gXng+gz+ceJTzg/vxNPyKCcG5Ap/2qW0lH+ZRcJTUgtmNZZIpiw56YD3T/ltc3wVIHEgFzCGUiZAaRtHJW3PGComDKd9Z3JPaZO1nuJlD999Kok4I9IEZjpu7g1mXlaioYsAwholJTsugoinEZ6JChaeT/92ZWY1Ua0vT5YJjz0QCGzlhJ12I751QFk1Lam9hwlhZ7LafDi1p8vhQuN1I5NOulgnoXwZboZ9/2jbNp63o1nq773jULJiAsMXY+Pv8SLCNKzVANyEK9ECYKG3DSxuVLIpX/j1cYWf/UH5FxQ5aiDYnZpBVblWfsQxPuyVjHnIyaAvw4LsTq4DfRG8JMqjjGr0IUGV6Xa/6/hCfx5ojvWFQ17YJeGHJMGAfPwvsTPhLTNl6Wm1Iw6Lt3N9KJ6VaGnJDuza/mJuTrTAdGhZ28bcevNq03vW3bFenLh0EC8zamBBA9eNuqqDak6Q1OzV3z6dRo=
  - secure: Tfm+Eu7st4Am1Pt4Zh2uD/QPbYMfrzjF6Mpkxa7lQpMzCMctm4+SZC8pd+GBrJdhXYIAyQhSmH3PaRzqfMwOpbLcbZiVS30zoV5aKwsD5lN7X2guA2yd87Xsp/kwJFoudMzvIf39DCYi/zB/hZFRu3KtVR46GWYgCmmYxzZzLJGz21G/auZP+q4Ncn/U8lcvOSERJLmThLc16znV4Sm8vLUy/ps3rWjnh5IBg+QOxtH7Gz0v2U57TxNWhyczbVL26rnK3d1TetZUTScA9Tuh7e1KVcY3NTAQUSGc0Lgnz/cCBhsaof89K6CwnF4RfUHFhYBUQ6lk4prT4FMioVaVVbt7bHp0vJp8P0Y6OYaSWlr1j1IuUd6FmwAjIM4A895/TZPIdj8KK3LDxynTSBmL6VO7EWrii/sYqV7/0CfcQBe4yWWdrvY9/ezIjZIt1pTLb9+UYmVh2uQNwJWfE/TSRev8pBEZDxJQEGsz7DZ+OQZ/6Q+u7I233VawQqklfaqQ7e18eHyHFaHPtcsUYjo+2rAwDzVtKw4bjNk3GZpIfLFXlZE9L/8qHAihP+HLk+T62U6HUnuSUCOIgELsNdLi3WSlc8DhpsDlqsqSTc5dUJUXb17ryxKflOutJnUavnxltoc3UtI2jNWPKqVswcXYFf8pOdczM/paif4P8dXOIoE=
  - secure: o1YQz4eyYlx6r/vO3SXwvQsY/fANpShiALMuPaUewd6d78oUX9E+1hW82NP8hznV62gkRxllgQV+frkyxAD1PaWyAyyWnbIDqJP/mV4QZ7xyNKxXzsynAhJsbH/NGRceQ7Nyk03ytFxU3VfdJ//m4Qnk9GQgnCfcnv7GcGrzlWW6Y/U8idEGFlYgNH1bLdhM50iJdN4iZsv69woT1fgd3LvmgMEcgZiAHe0HdcSa7XSPvaHGHn4Axj0fKp1Ydop+usYWBkwqL3Zp1gdPFCRZ7ZtTGx0XSQ/9f15mOgvbi9ZbTJUiCZUNTgCwRG+qDeFHk44R6HDzh2tpEKK+/rM6HEllqUdSnjgQPuBSPAzheEWz1WbeyI14rxbrBU44HXDE+HWR3XgF5ZD+waftwtLFz+J+YEgJ5564/rtRpH45OPig9JJ6qD958xTOOG+oW+aDwCCPi3aGTzFbEE5jlVbTzqqg8AVtKPZQqL7AncxdjxXeVhP4nwUKpNxGfU/SmoB4XvX7zmxvLuXIIS8ixpANm07Digqeg9iVst3EedkYkV+LwP69VD/x9/7MxVEer0Mkp0LKwlS8tRw8EBZ063DJm1RkhLwdCt2kTVwB4FX7eIB/7JUGdSuTw1emiPKNtjfYzyiT2JLa6Zd+2OWE9+tcKXeW4PcIjPvIFAUy6Z9Jksc=
  - secure: f0uCLszlxpYD5yuqpI9OESi6MnGt/c3guy3RmF6AcjimpG2hrkaZ3F1/TZg8FqR6gl1MC5pd/AQL7CH4O5wO0GLOFhWfZXGlgoFsY6vMObQx6hWvyzBHadIKiY6rW306aG1vAR5142pKilNErNnxMNs+H4+RYUoiwu+YoQwRXdwTRoHuO/aSVL4FA9seb83jxDh3IS9jNDynEzZN7ONJcOollMMjF9T7350VKCYYT1sXRqHPnglzJZxg7Vl6oZzvz3n1LbojHJxkBkCOpD/TJgbsky/4fOe56NXr7niIpZOZsspFdiIlkEEZnkY3IC/ntEfNecxvElbZ0orVmGUcGHVD7JqANwtdk+wML44/Q+t4Qpgc+InMVS98W0wGemq/XPpvzkLo6iW97AKW4C7Zetytb0IREeTd6MFl3BL6sn39nTURgF1ipWPXt6QwA0Wgc1gpXvOQ2NHRfPyoGxNswvGdNKoAkSyTRd5kb6mkhUjrZcsXzqw3KjE6+mf4m3KmOcOSoG1Y+WCU2D3sFVct9W3pNtM6v5TVn5VZSOHpWpDndSWOJdm6fVS3srzsqoWPi4Y/4lgbuae9iHMQQz0Bvv2xAQDrAFb+dAtUPeJJCJ+mTzk+BsToDQ+Z8ZG/2LNe8YIDMmOExUk6ROUO+SKu0xHdL6kSa8bPuTHCkceI8Mw=
  - secure: rqYoUIgzuOjm58iIntu+szFzUmTHJ0tqNVV7sOxs3649PLkpAbvwlaf1Ldg/B/+WTYw6mtOO+oyqHNvOBTWYjjpkjmLPN5MtwTAnH1/hi1IwnqHzWsldD1vLqEBfIvmnRBBefyQref1ynGbLYkPP6B8pj796KOC3H2RffUyIs2fStN0GNLCBLkTeKinAoQFYzyfAAHLDEvxb7UsEml/3EKbptj4LfJ59KuCMaX2p9iEZ1vWxkSsHNINcgeiTjHLEqFbAxkwA2/xsuzm43RRVNfQU5lFmkdM0tEeqCRsMpDKALuO5qQlcDdt6LjaFYWq1cUXOGLbX0yMXtTQFvKgZ7B9NTo6AjFc8ioR9NMf3ihVhJtyl2FX7KUvnY0DVyRMdsKxP6UcryrXkRr80P+Zn3TdbJaDE/p1OS/8Lvlz8W7pxP0aZas7z4GS5qMYb4hdH0D2eNVFTSkZERumv6iqCOhbtAgWpRmPVsywAqx5v7DbsezJaZtgeg08H+rFhwIBPSrBJmhhKV8vrypmS6a02CIZSJKSwmBskHZ7WixVQmi6BU92ngxMOYqy9bLt80DXGLF60KNzemaPgN/p45n5fZGewA0eKH0yX3CzOrM4FhQ8KbMdspJcm2JR57ISjN8MlphRfi9MSKoZEzXU0+f5qWpekMyLxDZ8Lg8dR6lKtN4k=
