zuul:
  routes:
    serviceA:
      path: /serviceA
      url: forward:/
    serviceB:
      path: /serviceB
      url: forward:/
    serviceC:
      path: /serviceC
      url: forward:/
    serviceD:
      strip-prefix: false
      path: /serviceD/**
      url: forward:/
    serviceE:
      path: /serviceE
      url: forward:/
  ratelimit:
    enabled: true
    policies:
      serviceA:
        limit: 10
        refresh-interval: 60
        type:
          - origin
      serviceB:
        limit: 2
        refresh-interval: 2
        type:
          - origin
      serviceD:
        limit: 2
        refresh-interval: 60
        type:
          - url
      serviceE:
        quota: 1
        refresh-interval: 60
        type:
          - origin
  strip-prefix: true

logging:
  level:
    ROOT: error